---
- name: Install NGINX From Apt-Get
  become: yes
  apt:
    name: nginx
    state: present

- name: Disable NGINX Default Virtual Host
  become: yes
  command:
    cmd: rm -f /etc/nginx/sites-enabled/default

- name: Check for NGINX Config File
  stat:
    path: /etc/nginx/sites-available/{{ domain_name }}.conf
  register: config_file_data

- name: Create NGINX Config File if it doesnt exist
  file:
    path: /etc/nginx/sites-available/{{ domain_name }}.conf
    state: touch
  when: not config_file_data.stat.exists

- name: Amend NGINX Config File
  become: yes
  blockinfile:
      path: /etc/nginx/sites-available/{{ domain_name }}.conf
      marker: ""
      block: |
        server {
            listen 80;
            location / {
                proxy_pass {{ server_url }};
                proxy_set_header Authorization "";
                proxy_read_timeout 90s;
            }
        }
        
- name: Check for linked NGINX Config File
  stat:
    path: /etc/nginx/sites-enabled/{{ domain_name }}.conf
  register: linked_file_data

- name: Link NGINX Config File if it doesnt exist
  become: yes
  command:
    cmd: ln -s /etc/nginx/sites-available/{{ domain_name }}.conf /etc/nginx/sites-enabled/{{ domain_name }}.conf
  when: not linked_file_data.stat.exists

- name: Make Sure NGINX Service Is Running
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes