# Setup nos-notification-service-go on server
---
- name: Create dir for AAA root certificate
  become: true
  ansible.builtin.file:
    path: /usr/local/share/ca-certificates/extra
    state: directory


- name: Copy AAA certificate to ca-certificates location
  become: true
  ansible.builtin.copy:
    src: AAACertificateServices.crt
    dest: /usr/local/share/ca-certificates/extra/AAACertificateServices.crt
  register: result


- name: Update certificates, if needed
  become: true
  ansible.builtin.command: update-ca-certificates
  when: result is changed


- name: Copy nginx config to sites available
  become: true
  ansible.builtin.template:
    src: nginx.conf.tpl
    dest: /etc/nginx/sites-available/{{ domain }}
    mode: 0644
    force: no


- name: Symlink site config to sites-enabled
  become: true
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ domain }}"
    dest: "/etc/nginx/sites-enabled/{{ domain }}"
    state: link


- name: UFW - Allow http/https connections
  become: true
  community.general.ufw:
    rule: allow
    name: "Nginx Full"


- name: UFW - Allow tcp connections for websockets
  become: true
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp


- name: Ensure config is valid
  become: true
  ansible.builtin.command: nginx -t
  changed_when: false


- name: Restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted


- name: Ensure notifications dir exists
  ansible.builtin.file:
    path: "{{ homedir }}/notifications"
    state: directory
    mode: '0755'


- name: Copy docker-compose.yml to notifications dir
  ansible.builtin.template:
    src: docker-compose.yml.tpl
    dest: "{{ homedir }}/notifications/docker-compose.yml"
    mode: 0644


- name: Ensure notifications/certs dir exists
  ansible.builtin.file:
    path: "{{ homedir }}/notifications/certs"
    state: directory
    mode: '0755'


- name: Copy certs to notifications dir
  ansible.builtin.copy:
    src: "{{ cert.path }}"
    dest: "{{ homedir }}/notifications/certs/{{ cert.file }}"
    mode: 0644
  loop:
    - file: "{{ notifications_apns_certificate }}"
      path: "{{ notifications_apns_certificate_path }}"
    - file: "{{ notifications_firestore_credentials_json }}"
      path: "{{ notifications_firestore_credentials_json_path }}"
  loop_control:
    loop_var: cert


- name: Copy pubsub cert to notifications dir
  ansible.builtin.copy:
    src: "{{ cert.path }}"
    dest: "{{ homedir }}/notifications/certs/{{ cert.file }}"
    mode: 0644
  loop:
    - file: "{{ notifications_google_pubsub_credentials_json }}"
      path: "{{ notifications_google_pubsub_credentials_path }}"
  loop_control:
    loop_var: cert
  when: notifications_google_pubsub_enabled is true


- name: Copy env file to notifications dir
  ansible.builtin.template:
    src: env.notifications
    dest: "{{ homedir }}/notifications/.env"
    mode: 0644


- name: ensure docker is running
  ansible.builtin.service:
    name: docker
    state: started


- name: Start up notifications
  community.docker.docker_compose:
    project_src: "{{ homedir }}/notifications"
    build: false
    restarted: true
  register: service_started
  retries: 5
  until: service_started is success


- name: Copy systemd service for notifications image update
  ansible.builtin.template:
    src: notifications-image-update.service.tpl
    dest: "{{ homedir }}/notifications/notifications-image-update.service"
    mode: 0644


- name: Copy systemd timer
  ansible.builtin.copy:
    src: notifications-image-update.timer
    dest: "{{ homedir }}/notifications/notifications-image-update.timer"
    mode: 0644


- name: Copy systemd shell script
  ansible.builtin.template:
    src: notifications-image-update.sh.tpl
    dest: "{{ homedir }}/notifications/notifications-image-update.sh"
    mode: 0755


- name: Symlink image update files to correct locations
  become: true
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: "{{ homedir }}/notifications/notifications-image-update.service"
      dest: /etc/systemd/system/notifications-image-update.service
    - src: "{{ homedir }}/notifications/notifications-image-update.timer"
      dest: /etc/systemd/system/notifications-image-update.timer
    - src: "{{ homedir }}/notifications/notifications-image-update.sh"
      dest: /usr/local/bin/notifications-image-update.sh


- name: Enable image update service and timer
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - notifications-image-update.service
    - notifications-image-update.timer


- name: Start image update service
  become: true
  ansible.builtin.systemd:
    name: notifications-image-update
    state: started
    daemon_reload: true