- name: Add all users listed to the host.
  ansible.builtin.user:
    name: {{ username }}
    state: present
    groups: sudo 
    append: true
    shell: "/bin/bash"
    create_home: true
  loop: "{{ gh_user_keys_to_add }}"
  loop_control:
    loop_var: username

- name: Create the .ssh folder for each user.
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh/"
    state: directory
    mode: "0700"
    owner: "{{ username }}"
    group: users

- name: Set ssh keys from Github for all listed users.
  ansible.posix.authorized_key:
    user: {{ username }}
    state: present
    key: https://github.com/{{ username }}.keys
  loop: "{{ gh_user_keys_to_add }}"
  loop_control:
    loop_var: username

- name: Setup passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regex: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Disable password login for everyone
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    validate: "/usr/sbin/sshd -t -f %s"

- name: Disable login for root
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    validate: "/usr/sbin/sshd -t -f %s"

- name: Restart sshd
  ansible.builtin.systemd:
    name: ssh
    daemon_reload: true
    state: restarted

- name: UFW - Allow SSH connections
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: UFW - Enable and deny by default
  community.general.ufw:
    state: enabled
    default: deny