---
- name: UFW - Allow http/https connections
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "80"
    - "443"


- name: Ensure services/relay exists
  ansible.builtin.file:
    path: "{{ homedir }}/services/relay"
    state: directory
    mode: '0755'


- name: Ensure strfry directory exists
  become: true
  ansible.builtin.file:
    path: "{{ homedir }}/services/relay/strfrydb"
    state: directory
    mode: '0755'


- name: Copy docker-compose.yml to relay dir
  ansible.builtin.template:
    src: docker-compose.yml.tpl
    dest: "{{ homedir }}/services/relay/docker-compose.yml"
    mode: '0644'


- name: Copy nginx-redirect.conf to relay dir
  become: true
  ansible.builtin.template:
    src: nginx-redirect.conf.tpl
    dest: "{{ homedir }}/services/relay/nginx-redirect.conf"
    mode: '0644'

- name: ensure docker is running
  ansible.builtin.service:
    name: docker
    state: started

- name: Start up docker services
  ansible.builtin.shell: "docker compose down && docker compose up -d"
  args:
    chdir: "{{ homedir }}/services/relay"
  register: service_started
  retries: 5
  until: service_started is success

- name: Setup the image updater
  ansible.builtin.include_role:
    name: image-update-service
  vars:
    service_name: strfry
    service_image: "{{ relay_server_image }}"
    service_image_tag: "{{ relay_server_image_tag }}"
    frequency: 3m
    working_dir: "{{ homedir }}/services/relay"

- name: Setup the health check
  ansible.builtin.include_role:
    name: health-check
  vars:
    health_check_endpoint: "{{ relay_health_check_endpoint }}"
    health_check_command: "{{ relay_health_check_command }}"