---
- name: Clone latest sentry repo
  become: true
  become_user: admin
  ansible.builtin.git:
    repo: https://github.com/getsentry/self-hosted.git
    dest: /home/{{ admin_username }}/sentry

- name: Copy sentry config
  become: true
  become_user: admin
  ansible.builtin.template:
    src: sentry.config.tpl
    dest: /home/{{ admin_username }}/sentry/sentry/config.yml
    mode: 0644

- name: Run sentry install/update script
  become: true
  become_user: admin
  ansible.builtin.command: 
    cmd: ./install.sh --no-report-self-hosted-issues
    chdir: /home/{{ admin_username }}/sentry

- name: Start services
  community.docker.docker_compose:
    project_src: /home/{{  admin_username }}/sentry
    build: false
    restarted: true
  register: output

- ansible.builtin.debug:
    var: output
      
- name: Set nginx config for all services
  become: true
  ansible.builtin.template:
    src: nginx.conf.tpl
    dest: /etc/nginx/sites-available/{{ inventory_hostname }}
    mode: 0644


- name: Symlink site config to sites-enabled
  become: true
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ inventory_hostname }}"
    dest: "/etc/nginx/sites-enabled/{{ inventory_hostname }}"
    state: link


- name: UFW - Allow http/https connections
  become: true
  community.general.ufw:
    rule: allow
    name: "Nginx Full"


- name: UFW - Allow tcp connections for websockets
  become: true
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp


- name: Ensure config is valid
  become: true
  ansible.builtin.command: nginx -t
  changed_when: false


- name: Restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted