CROSSPOSTING_LISTEN_ADDRESS= ":{{ crossposting_listen_address }}"
CROSSPOSTING_METRICS_LISTEN_ADDRESS=":{{ crossposting_metrics_listen_address }}"
CROSSPOSTING_ENVIRONMENT="{{ crossposting_environment }}"
CROSSPOSTING_TWITTER_KEY="{{ crossposting_twitter_key }}"
CROSSPOSTING_TWITTER_KEY_SECRET="{{ crossposting_twitter_key_secret }}"
CROSSPOSTING_DATABASE_PATH="/db/database.sqlite"
CROSSPOSTING_LOG_LEVEL={{ crossposting_log_level }}
CROSSPOSTING_PUBLIC_FACING_ADDRESS="https://{{ domain }}"
REDIS_URL={{ redis_url }}