---
# Deletes the feed of the given user id on all Planetary pubs. This is very innefficient
# as it rewrites the entire db. It also will cause the pub to be unresponsive for ~15
# minutes after the playbook ends while the flume views are rebuilt.
#
# Note: this does not publish a block message for the feed, so it could be resynced. 
# To block a user see the block-user.yml playbook.
#
# Usage: ansible-playbook delete-feed.yml -i {inventory} --extra-vars "feed_id='{feedID}'"
- name: Delete feed
  hosts: pubs
  serial: 1 # rolling update, don't bring all pubs down at once
  roles:
   - flumedb-delete
  tasks:
    - name: Stop sbot container
      docker_container:
        name: sbot
        state: absent
    - name: Stop healer container
      docker_container:
        name: healer
        state: absent

    - name:  Run delete script
      shell: 
        cmd: source /root/.profile && node ssb.js --id='{{ feed_id }}' --dir ~/ssb-pub-data
        chdir: flumedb-delete
      args:
        executable: /bin/bash

    - name: Clear flume views
      shell: 
        cmd: source /root/.profile && node delete-views --dir ~/ssb-pub-data
        chdir: flumedb-delete
      args:
        executable: /bin/bash

    # The deletion script messes up the permissions that Docker needs
    - name: Chown ssb-pub-data
      command: chown -R 1000:1000 ~/ssb-pub-data/flume

    - name: Start ssb-server
      shell: ./start-sbot

