---
# A playbook to deploy all of Planetary's rooms servers on existing DigitalOcean droplets.
#
#
# NOTE: Planetary.name should not be deployed using this playbook as some custom changes were made
# to it to support a wildcard SSL cert for aliases.
# To change the code running on planetary.name you should:
# 1. `cd go-ssb-room`
# 2. `git stash`
# 3. check out the branch you want to deploy
# 4. `git stash pop`
# 5. `docker-compose down && docker-compose build . && docker-compose up -d`

- name: Room Servers 
  hosts: rooms
  gather_facts: no
  serial: 2 # rolling update, don't bring all down at once
  pre_tasks:
    # SSH Host key checking
    # https://stackoverflow.com/a/54735937/982195
    - name: Check known_hosts for {{ inventory_hostname }}
      local_action: shell ssh-keygen -F {{ inventory_hostname }}
      register: has_entry_in_known_hosts_file
      failed_when: false
      changed_when: false
      ignore_errors: yes
    - name: Ignore host key for {{ inventory_hostname }} on first run
      when: has_entry_in_known_hosts_file.rc == 1
      set_fact:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    - name: Gather Facts
      setup:

  roles: 
    - common
    - digital-ocean
    - docker
    - ssb-room
