---
# This role installs planetary-graphql server with SSL

# NOTE! This role depends on go-ssb-room being run first
#
- name: Ensure planetary-graphql dir exists
  ansible.builtin.file:
    path: "{{ homedir }}/graphql" # we name it this to avoid confusion with the planetary-graphql repo
    state: directory
    mode: '0755'


- name: Get room key from go-ssb-room
  become: true
  ansible.builtin.shell: "cat secret | jq .id"
  args:
    chdir: "{{ homedir }}/room/ssb-go-room-secrets"
  register: get_admin_room_key


- set_fact:
    admin_room_key: "{{ get_admin_room_key.stdout|replace('\"','') }}"


- name: Copy docker-compose.yml to graphql dir
  ansible.builtin.template:
    src: docker-compose.yml.tpl
    dest: "{{ homedir }}/graphql/docker-compose.yml"
    mode: 0644


- name: Start up planetary-graphql
  become: true
  community.docker.docker_compose:
    project_src: "{{ homedir }}/graphql"
    build: false
  register: output


- name: Get graphql key
  become: true
  ansible.builtin.command:
  args:
    cmd: docker-compose exec -T -e "KEY_LOCATION=/tmp/planetary-graphql/secret" graphql node print-key.js
    chdir: "{{ homedir }}/graphql"
  register: get_graphql_key


- set_fact:
    graphql_key: "{{ get_graphql_key.stdout|replace('\"','') }}"


- ansible.builtin.debug:
    var: graphql_key


- name: Add graphql as member to room
  ansible.builtin.command:
  args:
    cmd: docker-compose exec -T room /app/cmd/insert-user/insert-user -repo /ssb-go-room-secrets -role admin -password {{graphql_password}} {{ graphql_key }}
    chdir: "{{ homedir }}/room"


- name: Restart planetary-graphql
  become: true
  community.docker.docker_compose:
    project_src: "{{ homedir }}/graphql"
    build: false
    restarted: true
  register: output
