# Setup nos-crossposting-service on server
---
- name: Copy nginx config to sites available
  become: true
  ansible.builtin.template:
    src: nginx.conf.tpl
    dest: /etc/nginx/sites-available/{{ domain }}
    mode: 0644
    force: yes


- name: Symlink site config to sites-enabled
  become: true
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ domain }}"
    dest: "/etc/nginx/sites-enabled/{{ domain }}"
    state: link


- name: Remove default config from sites-enabled
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent


- name: Archive existing configs that are now redirects
  become: true
  ansible.builtin.command: mv /etc/nginx/sites-available/{{ redirect }} /etc/nginx/sites-available/{{ redirect }}.bk
  args:
    removes: /etc/nginx/sites-available/{{ redirect }}
    creates: /etc/nginx/sites-available/{{ redirect }}.bk
  loop: "{{ redirects }}"
  loop_control:
    loop_var: redirect
  when: redirects is defined


- name: Remove redirect configs from sites-enabled
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/{{ redirect }}
    state: absent
  loop: "{{ redirects }}"
  loop_control:
    loop_var: redirect
  when: redirects is defined


- name: UFW - Allow http/https connections
  become: true
  community.general.ufw:
    rule: allow
    name: "Nginx Full"


- name: UFW - Allow tcp connections for websockets
  become: true
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp


- name: Ensure config is valid
  become: true
  ansible.builtin.command: nginx -t
  changed_when: false


- name: Restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted


- name: Ensure crossposting dir exists
  ansible.builtin.file:
    path: "{{ homedir }}/crossposting"
    state: directory
    mode: '0755'


- name: Copy docker-compose.yml to crossposting dir
  ansible.builtin.template:
    src: docker-compose.yml.tpl
    dest: "{{ homedir }}/crossposting/docker-compose.yml"
    mode: 0644


- name: Copy env file to crossposting dir
  ansible.builtin.template:
    src: env.tpl
    dest: "{{ homedir }}/crossposting/.env"
    mode: 0644


- name: ensure docker is running
  ansible.builtin.service:
    name: docker
    state: started


- name: Start up crossposting service
  ansible.builtin.shell: "docker compose down && docker compose up -d"
  args:
    chdir: "{{ homedir }}/crossposting"
  register: service_started
  retries: 5
  until: service_started is success


- name: Copy systemd service for crossposting image update
  ansible.builtin.template:
    src: crossposting-image-update.service.tpl
    dest: "{{ homedir }}/crossposting/crossposting-image-update.service"
    mode: 0644


- name: Copy systemd timer
  ansible.builtin.copy:
    src: crossposting-image-update.timer
    dest: "{{ homedir }}/crossposting/crossposting-image-update.timer"
    mode: 0644


- name: Copy systemd shell script
  ansible.builtin.template:
    src: crossposting-image-update.sh.tpl
    dest: "{{ homedir }}/crossposting/crossposting-image-update.sh"
    mode: 0755


- name: Symlink image update files to correct locations
  become: true
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: "{{ homedir }}/crossposting/crossposting-image-update.service"
      dest: /etc/systemd/system/crossposting-image-update.service
    - src: "{{ homedir }}/crossposting/crossposting-image-update.timer"
      dest: /etc/systemd/system/crossposting-image-update.timer
    - src: "{{ homedir }}/crossposting/crossposting-image-update.sh"
      dest: /usr/local/bin/crossposting-image-update.sh


- name: Enable image update service and timer
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - crossposting-image-update.service
    - crossposting-image-update.timer


- name: Start image update service
  become: true
  ansible.builtin.systemd:
    name: crossposting-image-update
    state: started
    daemon_reload: true
