- name: Perform a dist-upgrade.
  become: true
  ansible.builtin.apt:
    upgrade: dist
  register: dist_upgraded
  retries: 10
  delay: 5
  until: dist_upgraded is success


- name: update cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600


- name: Remove dependencies that are no longer required.
  become: true
  ansible.builtin.apt:
    autoremove: yes
  register: dependencies_removed
  retries: 10
  delay: 5
  until: dependencies_removed is success


- name: Disable snapd service if enabled
  become: true
  shell: if systemctl is-enabled --quiet snapd; then systemctl disable snapd && echo disable_ok ; fi
  register: output
  changed_when: "'disable_ok' in output.stdout"


- name: "Uninstall Snapd"
  become: true
  ansible.builtin.apt:
    pkg: snapd
    state: absent
  register: snapd_removed
  retries: 10
  delay: 5
  until: snapd_removed is success


- name: "Remove Snapd directory"
  become: true
  ansible.builtin.file:
    path: /root/snap
    state: absent


- name: Install common packages
  become: true
  ansible.builtin.apt:
    pkg:
      - curl
      - vim
      - git
      - ufw
      - rsync
      - jq
      - tmux
      - mosh
    state: latest
  register: pkgs_added
  retries: 10
  delay: 5
  until: pkgs_added is success


- name: UFW - Allow SSH connections
  become: true
  community.general.ufw:
    rule: allow
    name: OpenSSH


- name: UFW - Enable and deny by default
  become: true
  community.general.ufw:
    state: enabled
    default: deny


- name: Check if a reboot is required.
  become: true
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: no
  register: reboot_required_file


- name: Reboot the server (if required).
  become: true
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == true