- name: Remove old docker packages
  become: true
  ansible.builtin.apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent    


- name: Install required system packages
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest
    update_cache: true
    cache_valid_time: 3600


- name: Add Docker GPG apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present


- name: Add Docker Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable
    state: present


- name: Update apt and install docker-ce
  become: true
  ansible.builtin.apt:
    pkg: 
      - docker-ce
      - python3-docker
    state: latest
    update_cache: yes
    cache_valid_time: 3600


- name: Ensure docker cli-plugins dir exists
  become: true
  ansible.builtin.file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: '0755'


- name: Ensure group "docker" exists
  become: true
  ansible.builtin.group:
    name: docker
    state: present


- name: Add admin user to Docker
  become: true
  ansible.builtin.user:
    name: "{{ admin_username }}"
    groups: docker
    append: yes


- name: Download compose plugin
  become: true
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64
    dest: /usr/local/lib/docker/cli-plugins/docker-compose


- name: Ensure compose is executable
  become: true
  ansible.builtin.file:
    path: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: a+x


- name: Check docker compose works
  ansible.builtin.shell: docker compose version
  register: compose_version


- name: print version
  ansible.builtin.debug:
    msg: "{{ compose_version }}"


- name: add daemon.json config
  become: true
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0755


- name: Restart docker so config changes take effect
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    daemon_reload: true


- name: Reset ssh connection to allow changes to affect ansible user
  ansible.builtin.meta: reset_connection