---
- name: Set nostrface_dir
  ansible.builtin.set_fact:
    nostrface_dir: "{{ homedir }}/services/nostrface"


- name: Ensure nostrface_dir exists
  ansible.builtin.file:
    path: "{{ nostrface_dir }}"
    state: directory
    mode: '0755'


- name: Copy docker-compose.yml to nostrface_dir
  ansible.builtin.template:
    src: docker-compose.yml.tpl
    dest: "{{ nostrface_dir }}/docker-compose.yml"
    mode: 0644


- name: ensure docker is running
  ansible.builtin.service:
    name: docker
    state: started


- name: Start up docker services
  ansible.builtin.shell: "docker compose down && docker compose up -d"
  args:
    chdir: "{{ nostrface_dir }}"
  register: service_started
  retries: 5
  until: service_started is success


- name: Copy systemd service files for image update
  become: true
  ansible.builtin.template:
    src: "{{ file.src }}"
    dest: "{{ file.dest }}"
    mode: "{{ file.mode }}"
  loop:
    - src: nostrface-image-update.service.tpl
      dest: "/etc/systemd/system/nostrface-image-update.service"
      mode: "0644"
    - src: nostrface-image-update.sh.tpl
      dest: "/usr/local/bin/nostrface-image-update.sh"
      mode: "0755"
    - src: nostrface-image-update.timer.tpl
      dest: "/etc/systemd/system/nostrface-image-update.timer"
      mode: "0644"
  loop_control:
    loop_var: file


- name: Enable image update service and timer
  become: true
  ansible.builtin.systemd:
    name: "{{ systemd_unit }}"
    enabled: true
  loop:
    - nostrface-image-update.service
    - nostrface-image-update.timer
  loop_control:
    loop_var: systemd_unit


- name: Start image update service
  become: true
  ansible.builtin.systemd:
    name: nostrface-image-update
    state: started
    daemon_reload: true