---
- name: Copy nginx config to sites available
  become: true
  ansible.builtin.template:
    src: nginx.conf.tpl
    dest: /etc/nginx/sites-available/{{ domain }}
    mode: 0644
    force: no


- name: Symlink site config to sites-enabled
  become: true
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ domain }}"
    dest: "/etc/nginx/sites-enabled/{{ domain }}"
    state: link


- name: UFW - Allow http/https connections
  become: true
  community.general.ufw:
    rule: allow
    name: "Nginx Full"


- name: UFW - Allow tcp connections for websockets
  become: true
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp


- name: Ensure config is valid
  become: true
  ansible.builtin.command: nginx -t
  changed_when: false


- name: Restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted


- name: Ensure services/nostrface exists
  ansible.builtin.file:
    path: "{{ homedir }}/services/nostrface"
    state: directory
    mode: '0755'


- name: Copy docker-compose.yml to nostrface dir
  ansible.builtin.template:
    src: docker-compose.yml.tpl
    dest: "{{ homedir }}/services/nostrface/docker-compose.yml"
    mode: 0644


- name: Copy systemd service for nostrface  image update
  become: true
  ansible.builtin.template:
    src: nostrface-image-update.service.tpl
    dest: "/etc/systemd/system/nostrface-image-update.service"
    mode: 0644


- name: Copy systemd timer
  become: true
  ansible.builtin.copy:
    src: nostrface-image-update.timer
    dest: "/etc/systemd/system/nostrface-image-update.timer"
    mode: 0644


- name: Copy systemd shell script
  become: true
  ansible.builtin.template:
    src: nostrface-image-update.sh.tpl
    dest: "/usr/local/bin/nostrface-image-update.sh"
    mode: 0755


- name: Enable image update service and timer
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - nostrface-image-update.service
    - nostrface-image-update.timer


- name: Start image update service
  become: true
  ansible.builtin.systemd:
    name: nostrface-image-update
    state: started
    daemon_reload: true