---
- name: provision a new digital ocean droplet
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    domain: coolzach.ansible.fun # example, but you can overwrite this var at runtime
    do_droplet_name:  "{{ domain }}"
    do_oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
    do_droplet_size: s-1vcpu-1gb
    do_droplet_region: SFO3
    do_droplet_image: ubuntu-22-04-x64
    do_droplet_project: Nos
    do_droplet_enable_monitoring: true
    do_droplet_enable_backups: true
    do_droplet_tags:
      - development
    gh_user_keys_to_add:
      - cooldracula
      - zachmandeville
      - mplorentz
      - boreq
      - dcadenas
    admin_username: admin
    # these are inv examples, will be overwritten by any var passed in at runtime
    inv:  rss
    inv_groups:
      - rss
      - dev
    add_cloudflare_record: true
    cloudflare_email: code@solarpunk.cool
    cloudflare_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN')}}"
  roles:
    - new-do-droplet
  post_tasks:
    - name: Refresh Inventory
      ansible.builtin.meta: refresh_inventory


- name: Run additional plays
  hosts: "{{ inv_groups | join(':&') }}"
  gather_facts: no
  vars:
    ansible_user: admin
  roles:
    - node-exporter # always add node-exporter to our server
  pre_tasks:
    # SSH Host key checking
    # https://stackoverflow.com/a/54735937/982195
    - name: Check known_hosts for {{ inventory_hostname }}
      local_action: shell ssh-keygen -F {{ inventory_hostname }}
      register: has_entry_in_known_hosts_file
      failed_when: false
      changed_when: false
      ignore_errors: yes
    - name: Ignore host key for {{ inventory_hostname }} on first run
      when: has_entry_in_known_hosts_file.rc == 1
      set_fact:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
    - name: Gather Facts
      ansible.builtin.gather_facts:
  tasks:
    - name: Run additional roles
      ansible.builtin.include_role:
        name: "{{ additional_role }}"
      loop: "{{ additional_roles }}"  # expected to be given at runtime
      loop_control:
        loop_var: additional_role
