# Nostrface playbook
# This playbook deploys our nostrface service on an ubuntu server.
# It assumes you're running a hardened server, where you cannot login as root. (thus the ansible_user var)

- name: Deploy nostrface
  hosts: nostrface
  vars:
    ansible_user: admin
    domain: "{{ inventory_hostname }}"
  roles:
    - nostrface
