---
# tasks for hardening a server before further ansible work
- name: Install UFW
  become: true
  ansible.builtin.apt:
    pkg: ufw
    state: latest
    update_cache: true
    cache_valid_time: 3600


- name: UFW - Enable and deny by default
  become: true
  community.general.ufw:
    state: enabled
    default: deny


- name: UFW - Allow SSH connections
  become: true
  community.general.ufw:
    rule: allow
    name: OpenSSH